### PR TITLE
Update CoreDNS config to redirect `gitlab.bigbang.dev` to an internal location

### LINKED ISSUE #72: Get ability to use bigbang.dev domain back by using Istio ServiceEntry
Right now using bigbang.dev doesn't work, since services try to hit that from inside the cluster, and fail. We need to look into configuring Istio to redirect traffic, maybe using ServiceEntry. Until this is fixed, to get a working deployment one needs to use a real domain with real certs, configured to hit the computer's public IP address.

### PR DESCRIPTION
**Pull request by RothAndrew**
Alters the default coredns "Corefile" configuration on package install to include a rewrite plugin so that DNS lookups for `gitlab.bigbang.dev` originating within the cluster are redirected to the internal service address for gitlab.

Closes #72

### CODE REVIEW

**Comment by RothAndrew** [comment]
The test is failing but I suspect it's a problem with the test code, not this PR. I believe the "RunSSHCommand" is failing because the output that it collects gets to a certain size and the underlying function calls can't handle any more output, causing the connection to be terminated. I've seen this before and resolved it by breaking down large multi-stage commands into multiple single-stage ones, but it's happening with a single stage command now so I might need to reimplement that function.

**Comment by RothAndrew** [comment]
Unexpected things happened... Investigating

**Comment by blancharda** [comment]
> and I should get the same output as when I ran it on the host

The observed mismatch in behavior made sense based on how we had configured the coreDNS `rewrite` rule.

Traffic from outside the cluster was being routed through the istio public-ingressgateway (which notably, accepts `https` requests to `gitlab.bigbang.dev` on port `80`).

Inside the cluster however, we were using the DNS `rewrite` rule to send traffic directly to the gitlab webservice (which was expecting `http` requests on port `8080` / `8081`). Even then, making a request to `http://gitlab.bigbang.dev:8080` from inside the Jenkins pod would have been blocked by network policies in the gitlab namespace.

To mitigate the above, we've adjusted the `rewrite` rule to direct traffic to the public-ingressgateway, which should resolve the issues and align the behaviors when making a request from inside, or outside the cluster.

**Comment by blancharda** [comment]
This may be a non-issue related to my test environment - but it seems worth mentioning...

On restarting my test environment VM (or at some other point), it appears that K3S (my cluster distro) overwrote the changes to the coredns configmap.

Since this change is really only required to support local development and ephemeral tests, neither of which should require environment restarts, I'm not sure this is worth tracking down.. but we may be able to mitigate it by removing the "ownership" annotations.

**Pull request merged**
