### PR TITLE
ADR on SSO Provider

### LINKED ISSUE #23: ADR on SSO Provider
Outcome:
We want an Architecture Decision Record (ADR) on which tool is being used as the SSO provider for the "DI2-ME" software factory package, so that we can use it as a baseline when completing SSO-related work across the codebase.

### PR DESCRIPTION
**Pull request by RothAndrew**
Fixes #23 

The discerning reader will discover that... The decision hasn't been made yet! The Context section applies to both, so I wrote that, and left "TBD" in Decision and Consequences.

I propose we use the discussion here to make the decision, then I'll update the document once the decision is made and get it merged.

### CODE REVIEW

**Comment by RothAndrew** [comment]
I'm pretty torn, I can see either option being advantageous. If we can pull off GitLab it means a lot less operational complexity, but GitLab is a lot more unknown risk, and a LOT more trailblazing into unknown problem spaces.

**Comment by jeff-mccoy** [comment]
There's been a good bit of work to make BIg Bang tools work for other generic OIDC providers, so that part seems somewhat straightforward, but on CAC agreed we could run into the same chicken/egg issues as Keycloak.  Though I will say it would be much less complex to deploy/maintain just Gitlab vs Gitlab + Keycloak.

**Comment by RothAndrew** [comment]
Maybe we should do a spike on just the CAC portion? To see if it is reasonably straightforward or if there are a bunch of dragons

**Comment by RothAndrew** [comment]
Ready for final review and merge

**Review by jeff-mccoy — APPROVED** [review]
Lgtm thx

**Pull request merged**
