### PR TITLE
Feature/update gitlab redis namespace

### PR DESCRIPTION
**Pull request by brianrexrode**
moved redis deployment to gitlab-redis namespace and refactored all references to match.

relocated the egress-istiod networkPolicy to avoid the commonLabel `owner: softwarefactoryaddons` getting set in the base kustomization.yaml which was getting added to the egress rule and causing failures.

### CODE REVIEW

**Comment by RothAndrew** [comment]
I pulled it down and ran it and it looks fine. Not sure why the E2E pipeline would be failing. Something flaky/intermittent maybe

**Comment by brianrexrode** [comment]
yeah, i tried rerunning the e2e with no luck but did do a new deployment from this branch this morning and  verified everything came up cleanly

**Review by RothAndrew — APPROVED** [review]

**Pull request merged**
