### PR TITLE
Add Minio and tell GitLab to use it

### LINKED ISSUE #43: Turn on Minio
We want minio to be available in the cluster, so that other services like GitLab can use it instead of its internal one. Minio Operator already deploys but an instance of Minio is currently turned off.

### LINKED ISSUE #44: Make GitLab use the Minio that's already available
After #43 there will already be a Minio running the cluster. We should tell GitLab to use it instead of deploying its own.

### PR DESCRIPTION
**Pull request by RothAndrew**
Fixes #43
Fixes #44

### CODE REVIEW

**Comment by RothAndrew** [comment]
@Racer159 and/or @mikevanhemert if you could give this a once-over I would be eternally grateful

**Comment by mikevanhemert** [comment]
@RothAndrew looks clean, great job! Should the README be updated to describe the GitLab's updated dependency on Minio and configuration changes downstream users are likely to change (specifically, `bigbang/common/values.yaml`'s `gitlab.objectStorage.region` and `minio.values.tenants.buckets[*].region`)?

**Review by mikevanhemert — APPROVED** [review]

**Comment by RothAndrew** [comment]
> @RothAndrew looks clean, great job! Should the README be updated to describe the GitLab's updated dependency on Minio and configuration changes downstream users are likely to change (specifically, `bigbang/common/values.yaml`'s `gitlab.objectStorage.region` and `minio.values.tenants.buckets[*].region`)?

Yes definitely, still need to go through and update docs

**Pull request merged**
