### PR TITLE
WIP: Get ability to use `bigbang.dev` domain back by using Istio ServiceEntry

### LINKED ISSUE #72: Get ability to use bigbang.dev domain back by using Istio ServiceEntry
Right now using bigbang.dev doesn't work, since services try to hit that from inside the cluster, and fail. We need to look into configuring Istio to redirect traffic, maybe using ServiceEntry. Until this is fixed, to get a working deployment one needs to use a real domain with real certs, configured to hit the computer's public IP address.

### PR DESCRIPTION
**Pull request by RothAndrew**
https://istio.io/latest/docs/reference/config/networking/service-entry/

Fixes #72

### CODE REVIEW

**Comment by RothAndrew** [comment]
Not able to get it working given a few different iterations. Moving on to more fruitful efforts. @jeff-mccoy if you get some time I would love another set of eyes on this.

Docs I've been using:

* https://istio.io/latest/docs/reference/config/networking/service-entry/
* https://discuss.istio.io/t/best-way-to-to-route-public-service-dns-internally/9390/3
* https://thenewstack.io/trying-out-istios-dns-proxy/

**Comment by jeff-mccoy** [comment]
Played with this for a while and it looks like the issue might be missing a config for the operator:

```
spec:
 meshConfig:
   defaultConfig:
     proxyMetadata:
       ISTIO_META_DNS_CAPTURE: "true"
```
And the SE look more like:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-https
  namespace: jira
spec:
  hosts:
    - gitlab.bigbang.dev
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: STATIC
  endpoints:
    - address: 3.19.25.126
    - address: 18.189.172.219
    - address: 3.133.197.0
```

But the istio docs have been down and giving me a headache for a couple days now......

**Comment by RothAndrew** [comment]
What are the IPs listed in the endpoints section? They look to be potentially environment specific, which wouldn't be the end of the world, but obviously not ideal

**Comment by RothAndrew** [comment]
When I add

```
spec:
 meshConfig:
   defaultConfig:
     proxyMetadata:
       ISTIO_META_DNS_CAPTURE: "true"
```

to the IstioOperator config, I get this error:

image

I forked the Repo1 chart so I could add it, just to test whether it would work. Here's the changed line in case someone else feels like testing: https://github.com/RothAndrew/istio-controlplane/blob/870068e697d5a48b33f95a201081463a7c5256e2/chart/templates/controlplane.yaml#L97

My branch of DI2-ME that can be used for testing this: https://github.com/RothAndrew/zarf-package-software-factory/tree/feature/service-entry

**Comment by RothAndrew** [comment]
Putting this to the side for right now to focus on something I already know how to get working. Very much want to come back to this to get it working, or if anyone out there has seen something like this that would be huge.

**Pull request closed without merging**
