### PR TITLE
Change centralized MinIO to MinIO per service that needs buckets

### PR DESCRIPTION
**Pull request by RothAndrew**
Also:

* Re-enable istio injection in GitLab namespace
* Add a new make target in the day2 folder `nuke-and-rebuild` which will nuke the cluster, rebuild the zarf package, and redeploy. It's a good 10-15 minutes faster than tearing down the instance and re-running the terratest tests due to not having to re-download all the docker images. `nuke-and-rebuild` needs to be run from inside the instance.
* Add missing `gitlab-redis` component in the day2 zarf.yaml
* Add ADR for the minio stuff
* ~~Disable minio networkpolicies~~ (fixed, re-enabled)
* Add Istio as a dependsOn for the databases so they consistently get sidecars

### CODE REVIEW

**Review by brianrexrode — APPROVED** [review]
This configuration/branch deployed successfully on back-to-back occasions for me. 👍

**Comment by RothAndrew** [comment]
@ntwkninja @kirankt any objections to calling the ADR in this PR accepted?

**Comment by RothAndrew** [comment]
@brianrexrode one more review pls

**Review by brianrexrode — APPROVED** [review]
👍

**Pull request merged**
