### PR TITLE
Run E2E tests in main

### LINKED ISSUE #442: Move E2E test from PRs to main
Current process:

* E2E tests run as part of PRs. If they pass, the PR can be merged into main
* PRs are required to be up to date with the latest changes in main before being merged
* Because of this, the tests are not run again in main. There would be no point, since they would always run against the same commit as before

Advantages to current process:

* Broken code is almost never merged into main since there's a quality gate that happens before the merge

Drawbacks to current process:

* PRs take a long time to merge because the E2E tests take a long time to run (they are up to ~55 minutes). Even 1-line changes or changes to things that don't affect the codebase (like documentation) take a long time
* If `main` changes before the PR gets merged the tests need to be run again after the new changes are integrated into the feature branch

Proposed new process:

* Only run tests in PRs that take less than 5 minutes. Anything longer than that is not required and not run automatically until the change hits `main`
* Run all tests on each new commit to `main`
* Immediately prioritize broken code that has made it into `main` (pipeline red to pipeline green) over all other work.
* Longer tests can still be run in a PR if desired by using chatops comments (`/test all`). All tests still run again once the change hits main, even if it isn't technically needed. We may want to keep doing this for any PRs that external contributors create since broken code will most likely end up on our plates to fix rather than the 3rd party contributor's.

Advantages to new process:

* Quality gates on PRs are now much shorter
* Process is much closer to Trunk-Based Development without losing the goodness of using PRs in an open source product. Feature branch TTL is likely significantly reduced.

Disadvantages to new process:

* `main` won't be as "clean", but we can mitigate by adding a note to the docs that `main` is bleeding edge and never guaranteed to be of the same stabiliy/quality as a published release

### PR DESCRIPTION
**Pull request by RothAndrew**
Closes #442

### CODE REVIEW

**Comment by RothAndrew** [comment]
Need to change the branch trigger back to `main` but otherwise I think this is ready. When the current run (triggered by `push`) finishes I'm gonna run a chatops command as well to make sure existing functionality didn't break.

**Review by brianrexrode — APPROVED** [review]
👍

**Comment by RothAndrew** [comment]
@brianrexrode one more review pls

**Review by brianrexrode — APPROVED** [review]
lgtm

**Pull request merged**
