### PR TITLE
Zarf v0.15.0 compatibility

### LINKED ISSUE #24: Update compatibility to Zarf v0.15.0
Outcome:
We want to update the package to be compatible with the latest version of Zarf, which is currently v0.15.0

### PR DESCRIPTION
**Pull request by RothAndrew**
### To-Do

- [x] Compatible with Zarf v0.15.X
- [x] Add Jenkins VirtualService back in
- [x] Smoke-Test all services
- [x] Update docs

### Changes
- Now compatible with Zarf v0.15.X. Not backwards-compatible with earlier versions. 
- Istio VirtualServices now available on port 443 instead of 9443
- Disable SonarQube for now due to [this bug](https://repo1.dso.mil/platform-one/big-bang/apps/developer-tools/sonarqube/-/issues/35)
    - Fixable with some elbow grease, but we have bigger fish to fry right now
- Disable Mattermost for now
    - ImagePullBackOff on the Minio containers
    - MM shouldn't be deploying its own minio, there's already MinioOperator being deployed
    - It's using a custom version, since the version specified in v1.17.0 of the Big Bang chart has problems. Better to just upgrade the Big Bang version which will automatically upgrade MatterMost too
    - We have bigger fish to fry than getting this working right now (GitLab, Jenkins, Jira, Confluence, SSO, CAC auth, 2FA)

Fixes #24

### CODE REVIEW

**Comment by RothAndrew** [comment]
Looks to be working pretty well, but with a custom-built Zarf binary that increases the number of retires for the `scripts.before:` scripts from 60 to 300. See https://github.com/defenseunicorns/zarf/pull/339 and https://github.com/defenseunicorns/zarf/issues/338. Need to figure out that issue first before this can merge, unless we come up with a different solution first.

image

**Comment by RothAndrew** [comment]
@jeff-mccoy @YrrepNoj Thoughts on how I could do this differently than I am currently for having Jira, Confluence, and Jenkins wait until Istio is up and running? Here's how I'm doing it currently:

```yaml
scripts:
      retry: true
      before:
        # Check to see if istiod is running before trying to deploy. If Istio is running then so is Gatekeeper. This is a poor man's version of "DependsOn" since we aren't doing real gitops yet
        - |
          test $(/usr/sbin/kubectl get pods -n istio-system -l app=istiod --field-selector=status.phase=Running -o json | ./jq -r '.items | length') -gt 0
```

The issues are:

* Zarf has a hard-coded timeout right now of ~2 minutes. Istio takes longer than 2 minutes to come up
* I'm introducing dependencies on the binaries `/usr/sbin/kubectl`, `./jq`, and `test`. `test` is a shell builtin, `jq` is included in the package, and `/usr/sbin/kubectl` is present as long as I'm using the `k3s` component. Though, it's ugly/hacky to be bringing in binaries like this

The long term solution would be #11, but that's a chunk that I don't want to bite off right now unless I absolutely have to.

I'm ashamed of myself for even thinking it, but I could do a `sleep 300` before starting the checks for Istio to come up, or I could hack away at the script that's there until it internally waits, which Zarf wouldn't see and think the script is still just running.

**Comment by jeff-mccoy** [comment]
yeah it's a non-trivial problem, let me think on this one...

**Comment by RothAndrew** [comment]
For right now I think what I want to do is modify the script to do its own timeout, [kinda like this](https://github.com/defenseunicorns/zarf/blob/0c85a33c4e312593afebbd12753f725000a97bca/test/e2e/e2e_example_game_test.go#L72), and add the `kubectl` binary as another component next to `jq` so that I can use it without needing to expect it to be there. This is ugly, but it won't require bandaid measures in the Zarf codebase and will hold up fine until we can get to #11

**Comment by RothAndrew** [comment]
Smoke tests, after running `ssh -L 9443:localhost:443 ubuntu@<TheInstanceHostname>` and deleting the `misdirected-request` EnvoyFilter (since I'm using port 9443 locally), on a M6i.8xlarge EC2 instance running Ubuntu 20.04:

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by RothAndrew** [comment]
@david--wright can I get you to try this out for me using Zarf v0.15.0? I'm still updating docs, but the important bits shouldn't be any different than the previous version that used Zarf v0.14.0, other than the `zarf init` components will be different.

**Comment by RothAndrew** [comment]
I believe this is ready to merge. Requesting one review from either @jeff-mccoy or @YrrepNoj and one from @david--wright

**Comment by jeff-mccoy** [comment]
I'll take some time to test it out late afternoon if that's okay @RothAndrew

**Comment by RothAndrew** [comment]
Works for me. Thanks! 😄

**Comment by david--wright** [comment]
All of the expected services deployed and were accessible for me. The deploy went a lot smoother than any of the previous deploys have gone. The one thing that didn't work straight off was k9s. I could check everything with kubectl so that wasn't an issue. Just a difference from previous versions.

**Comment by jeff-mccoy** [comment]
K9s is now "zarf tools monitor"

**Comment by RothAndrew** [comment]
@david--wright K9s is now `zarf tools k9s`. It was moved to being bundled in with Zarf instead of a binary being added to the system.

**Comment by jeff-mccoy** [comment]
That one too 😂 there are multiple aliases--I use "zarf t m".

**Comment by jeff-mccoy** [comment]
Man Big Bang is so dang slow 😆.  I didn't wait for it all to spin up, but mostly looked good to me.  I was actually testing it on EKS with [PR #239 from Zarf](https://github.com/defenseunicorns/zarf/pull/329).  

Screen Shot 2022-02-28 at 11 33 41 PM

One thing I think we should do though--not a huge fan of the bash script wait or the extra binaries you had to add.  However, we already have a wait/loop function in zarf that would be trivial to expose to package authors to remove this concern.  What do you think of merging this now and then opening an issue to add a "waitForPodByLabel" or something to component definitions to block until the specified pod is ready.

**Review by jeff-mccoy — APPROVED** [review]
LGTM, see prev comments about the wait scripts

**Comment by RothAndrew** [comment]
I like the idea of the new feature, though for this particular use case it is only a stopgap. IMO the real fix is to implement #11 which would give us actual “dependsOn” capability from Flux

**Pull request merged**
