### PR TITLE
Add neuvector

### PR DESCRIPTION
**Pull request by corang**
unsure if it should be a part of the public ingressgateway or if we should enable a private one and put administrative stuff like neuvector on it. See #605 

- [x] ingress decision
- [x] static resource amounts
- [x] docs
- [x] zarf package for updating CVE db?
- [x] ~~sso values in encrypted bb vals~~

### CODE REVIEW

**Comment by corang** [comment]
Going to be adding internal admin lb

**Review by anthonywendt — DISMISSED** [review]
LGTM

**Review by anthonywendt — APPROVED** [review]

**Pull request merged**
